### ISSUE TITLE
Using sphinx-lint

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-es#2200]
Hi!

I'm developping https://pypi.org/project/sphinx-lint/, and it's now able to lint `.po` files. We use it on python-docs-fr, it's able to spot many typos, like:

```
tutorial/controlflow.po:199: missing space before default role: 'ula`!else`'. (missing-space-before-default-role)
tutorial/controlflow.po:135: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
reference/expressions.po:1960: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
reference/expressions.po:1960: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
```

`sphinx-lint` show never ever give a false positive (I know, I know, utopia...) but please, please, report any false positive to https://github.com/sphinx-contrib/sphinx-lint/issues if you find one.

**Comment by cmaureir** [comment]
thanks for the heads-up, I have been using a [local variation of a script we have](https://github.com/python/python-docs-es/pull/1783) to check inconsistencies between italics and bold formatting, because we had the bad practice of adding stars around English words. That will certainly solve the same issue and even get more things :+1:

**Comment by JulienPalard** [comment]
sphinx-lint is very Sphinx oriented, not `.po` file oriented, maybe keeping your script in addition to sphinx-lint may make sense :)

**Comment by rtobar** [comment]
I just run the tool against `library/` as a whole and it spit out a loooot of messages, so I thought that maybe it didn't work with our po files. After closer inspecting two of these files I found that they were indeed proper errors, so I went and fixed them for those two files, as a sample: https://github.com/python/python-docs-es/pull/2205

So it seems like it's working as intended, at least from my initial inspection. I'll leave a suggestion on the issue tracker, but otherwise so far so good.

**Comment by rtobar** [comment]
For reference, I left a suggestion to add the ability to sort output (https://github.com/sphinx-contrib/sphinx-lint/issues/50) and some patches with an initial implementation (https://github.com/sphinx-contrib/sphinx-lint/pull/51).

**Comment by rtobar** [comment]
At the beginning of this exercise there were ~320 linting errors in `library/` alone. After #2205 and #2210 there are none, but there are still others across the project:

```
$> sphinx-lint **/*po | wc -l
186
```

**Comment by rtobar** [comment]
#2210 now fixes all remaining errors.

Most of the errors were due to double backticks not being properly separated from their surrounding words, or being imbalanced. Other common mistake was missing the final `_` after hyperlinks. Overall it was a good exercise, and it'd be great to have this tool running as part of the automatic tests.

Fixing these issues also let pospell find two new problems. Most importantly, it found an error that was due to a ``backtick`` not separated with spaces from its previous word, which sphinx-lint didn't find. The sentence had this form: `some words *with stars*''backtick-words''` (using single quote because I don't know how to escape backticks here...), so I'm guessing the sphinx-lint check didn't catch that one.

**Comment by rtobar** [comment]
Closing since we successfully adopted sphinx-lint some time ago, and have been keeping up with newer versions as well.
