### ISSUE TITLE
3.8 index page shows Python 3.7 version on Read the Docs

### ISSUE THREAD

**Issue by humitos** [python/python-docs-es#704]
This page https://python-docs-es.readthedocs.io/es/3.8/ shows Python 3.7 and it should show Python 3.8, as https://docs.python.org/es/3.8/ shows.

It may happened that the `cpython/` module was updated by mistake with an old commit. I'm not sure, but that's what I'd guess. We should check that.

**Comment by FedericoJurio** [comment]
Your guess seems to be accurate since the title is filled with the version that comes from `cpython/` https://github.com/python/python-docs-es/blob/1f7b067bd2fd2b64e6d30f26d9869def3017b3f1/conf.py#L27

**Comment by cmaureir** [comment]
```
% git log --patch-with-stat -- cpython | grep commit
commit ba262d260de2b4d1a3ab8d7db29966a8c1e52031
-Subproject commit 70fe95cdc9ac1b00d4f86b7525dca80caf7003e1
+Subproject commit 48ef06b62682c19b7860dcf5d9d610e589a49840
commit 5a3b65c4ff4335d3d92ee109e3960f3667492b68
-Subproject commit 48ef06b62682c19b7860dcf5d9d610e589a49840
+Subproject commit 70fe95cdc9ac1b00d4f86b7525dca80caf7003e1
commit 028a81e58e80ac73039d2dde9f56a8f2555ef1e7
+Subproject commit 48ef06b62682c19b7860dcf5d9d610e589a49840
```

```
git log -- cpython
commit ba262d260de2b4d1a3ab8d7db29966a8c1e52031
Author: Carlos A. Crespo <lvccrespo@gmail.com>
Date:   Sat Jun 6 18:25:59 2020 -0300

    continuando con la traducción

commit 5a3b65c4ff4335d3d92ee109e3960f3667492b68
Author: Manuel Kaufmann <humitos@gmail.com>
Date:   Mon May 4 22:48:55 2020 +0200

    Update cpython submodule to point to 3.8 branch

commit 028a81e58e80ac73039d2dde9f56a8f2555ef1e7
Author: Manuel Kaufmann <humitos@gmail.com>
Date:   Fri May 1 21:20:54 2020 +0200

    Submodule 3.7
```

The main issue is that we cannot revert ba262d260de2b4d1a3ab8d7db29966a8c1e52031 because removing the submodule update, the submodule will remain on the same version.
That commit seems to be on 3.7, problem is that we cannot simply checkout the 70fe95cdc9ac1b00d4f86b7525dca80caf7003e1 commit from the submodule, because it's not in any tree, so what I did was:

* on the submodule `git pull origin 3.8` (because I knew it was on the 3.8 branch)
* `git checkout 70fe95cdc9ac1b00d4f86b7525dca80caf7003e1` to return to the last submodule commit we had working
* add and commit the submodule sha update.

The problem with that is that that submodule version it's  **3.8.3rc1**

![Screenshot_2020-08-18 Documentación 3 8 3rc1](https://user-images.githubusercontent.com/177982/90566594-0c482a00-e1a9-11ea-85d4-a4d80fc189f7.png)

IIRC that was the version we had in the internal site: https://python-docs-es.readthedocs.io/es/3.8/

We could get the latest commit from the 3.8 branch, and update to it: 
2bcd0fe7a5d1a3c3dd99e7e067239a514a780402
but the problem with this approach is that there might be new documentation on the base files we have been translating.

Should we stick with the result from the image?

**Comment by aroquega** [comment]
¿@cmaureir  este problema todavía sigue? por lo que veo ya no aparece la 3.7 en el read-the-docs, creo que se debe cerar este issue o cambiar el nombre.

**Comment by cmaureir** [comment]
Si ya está listo :+1:
